### ISSUE TITLE
Identify Updates Needed for Astromer

### ISSUE THREAD

**Issue by jessespencersmith** [vanderbilt-data-science/waveform-architecture#2]
Explore [Astromer](https://arxiv.org/abs/2205.01677) and determine what updates might be needed:
- Context length
- Positional encoding (RoPE)
- FlashAttention

Examine for other possible updates.

Check to see if any forks have been made them might have already done this. Propose the updates at the next meeting.

**Comment by FrostNT1** [comment]
Split into separate tasks.
